import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Providers from "@/components/shared/Providers";
import { Suspense } from "react";
export const metadata: Metadata = {
  title: "ecom",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang={"en"}>
      <body className={` bg-main-6 dark:bg-dark-2`}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <Providers>
            <Suspense fallback='loading'>{children}</Suspense>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
